/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chiappalatalpa;

import javax.swing.JButton;

/**
 *
 * @author bianconi.yurinabil
 */
public class Interfaccia extends javax.swing.JFrame {
    private JButton[] buche;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());
    private int punteggio = 0;
    private Talpa talpa;
    private int colpi = 0;
    private int tempo = 30;
    private Thread threadTalpa;
    private Thread threadTempo;
    private String nomeGiocatore;
    private Classifica classifica = new Classifica();
    private void colpisciBuca(JButton b){ //METODO IMPLEMENTATO CON AI

        if(b.getText().equals("🐹")){
            colpi++;
            punteggio += 10;

        }else{

            punteggio -= 5;
            if (punteggio < 0){
                punteggio = 0;
            }

        }

        labelPunteggio.setText("Punteggio: " + punteggio);
        labelColpi.setText("Colpi: " + colpi);

    }
    private void avviaTimer(){

    threadTempo = new Thread(() -> {

        while(tempo > 0){

            try{

                Thread.sleep(1000);

                tempo--;

                labelTempo.setText("Tempo: " + tempo);

            }catch(Exception e){
                e.printStackTrace();
            }

        }

        fineGioco();

    });

    threadTempo.start();

}
    
    private void fineGioco(){

    talpa.ferma();

    classifica.salvaPunteggio(nomeGiocatore, punteggio);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Tempo scaduto!\nPunteggio: " + punteggio
    );

    classifica.stampaClassifica();

}

    /**
     * Creates new form Interfaccia
     */
    public Interfaccia() {
        
        initComponents();
        nomeGiocatore = javax.swing.JOptionPane.showInputDialog(
        this,
        "Inserisci il tuo nome:"
        );
        buche = new JButton[] {bottoneBuca1, bottoneBuca2, bottoneBuca3, bottoneBuca4, bottoneBuca5, bottoneBuca6};
        for (JButton b : buche){
            b.addActionListener(e -> colpisciBuca(b));
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bottoneBuca4 = new javax.swing.JButton();
        bottoneBuca1 = new javax.swing.JButton();
        bottoneBuca2 = new javax.swing.JButton();
        bottoneBuca5 = new javax.swing.JButton();
        bottoneBuca3 = new javax.swing.JButton();
        bottoneBuca6 = new javax.swing.JButton();
        bottoneGioca = new javax.swing.JButton();
        labelPunteggio = new javax.swing.JLabel();
        labelColpi = new javax.swing.JLabel();
        labelTempo = new javax.swing.JLabel();
        comboDifficolta = new javax.swing.JComboBox<>();

        jButton2.setText("jButton1");

        jButton6.setText("jButton1");

        jButton7.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(null);

        bottoneBuca4.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca4);
        bottoneBuca4.setBounds(60, 240, 100, 90);

        bottoneBuca1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca1);
        bottoneBuca1.setBounds(60, 60, 100, 90);

        bottoneBuca2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca2);
        bottoneBuca2.setBounds(180, 150, 100, 90);

        bottoneBuca5.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca5);
        bottoneBuca5.setBounds(300, 240, 100, 90);

        bottoneBuca3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca3);
        bottoneBuca3.setBounds(300, 60, 100, 90);

        bottoneBuca6.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca6);
        bottoneBuca6.setBounds(420, 160, 100, 90);

        bottoneGioca.setBackground(new java.awt.Color(0, 0, 0));
        bottoneGioca.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        bottoneGioca.setForeground(new java.awt.Color(242, 242, 242));
        bottoneGioca.setText("GIOCA");
        bottoneGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneGiocaActionPerformed(evt);
            }
        });
        jPanel1.add(bottoneGioca);
        bottoneGioca.setBounds(600, 160, 130, 40);

        labelPunteggio.setFont(new java.awt.Font("Rubik", 0, 21)); // NOI18N
        labelPunteggio.setText("punteggio: 0");
        jPanel1.add(labelPunteggio);
        labelPunteggio.setBounds(600, 200, 180, 26);

        labelColpi.setFont(new java.awt.Font("Rubik", 0, 21)); // NOI18N
        labelColpi.setText("colpite: 0");
        jPanel1.add(labelColpi);
        labelColpi.setBounds(600, 230, 130, 26);

        labelTempo.setFont(new java.awt.Font("Rubik", 0, 21)); // NOI18N
        labelTempo.setText("tempo: 30");
        jPanel1.add(labelTempo);
        labelTempo.setBounds(600, 260, 130, 26);

        comboDifficolta.setBackground(new java.awt.Color(0, 0, 0));
        comboDifficolta.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        comboDifficolta.setForeground(new java.awt.Color(242, 242, 242));
        comboDifficolta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facile", "Media", "Difficile" }));
        jPanel1.add(comboDifficolta);
        comboDifficolta.setBounds(600, 100, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneGiocaActionPerformed
        //METODO IMPLEMENTATO CON AI
        punteggio = 0;
        colpi = 0;
        tempo = 30;

        labelPunteggio.setText("Punteggio: 0");
        labelColpi.setText("Colpi: 0");
        labelTempo.setText("Tempo: 30");

        int velocita = 1500;

        String difficolta = comboDifficolta.getSelectedItem().toString();

        if(difficolta.equals("Facile"))
            velocita = 1500;

        if(difficolta.equals("Media"))
            velocita = 1000;

        if(difficolta.equals("Difficile"))
            velocita = 600;

        talpa = new Talpa(buche, velocita);

        threadTalpa = new Thread(talpa);
        threadTalpa.start();

        avviaTimer();


    }//GEN-LAST:event_bottoneGiocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        Interfaccia frame = new Interfaccia();
        frame.setSize(1000,600);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneBuca1;
    private javax.swing.JButton bottoneBuca2;
    private javax.swing.JButton bottoneBuca3;
    private javax.swing.JButton bottoneBuca4;
    private javax.swing.JButton bottoneBuca5;
    private javax.swing.JButton bottoneBuca6;
    private javax.swing.JButton bottoneGioca;
    private javax.swing.JComboBox<String> comboDifficolta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelColpi;
    private javax.swing.JLabel labelPunteggio;
    private javax.swing.JLabel labelTempo;
    // End of variables declaration//GEN-END:variables
}
