/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chiappalatalpa;

import javax.swing.JButton;

/**
 *
 * @author bianconi.yurinabil
 */
public class Interfaccia extends javax.swing.JFrame {
    private JButton[] buche;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());
    private int punteggio = 0;
    private Talpa talpa;
    private void colpisciBuca(JButton b){ //METODO IMPLEMENTATO CON AI

        if(b.getText().equals("🐹")){

            punteggio += 10;
            b.setText("");
            b.setBackground(new java.awt.Color(102,51,0));

        }else{

            punteggio -= 5;

        }

        labelPunteggio.setText("Punteggio: " + punteggio);

    }

    /**
     * Creates new form Interfaccia
     */
    public Interfaccia() {
        
        initComponents();
        buche = new JButton[] {bottoneBuca1, bottoneBuca2, bottoneBuca3, bottoneBuca4, bottoneBuca5, bottoneBuca6};
        for (JButton b : buche){
            b.addActionListener(e -> colpisciBuca(b));
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bottoneBuca4 = new javax.swing.JButton();
        bottoneBuca1 = new javax.swing.JButton();
        bottoneBuca2 = new javax.swing.JButton();
        bottoneBuca5 = new javax.swing.JButton();
        bottoneBuca3 = new javax.swing.JButton();
        bottoneBuca6 = new javax.swing.JButton();
        bottoneGioca = new javax.swing.JButton();
        labelPunteggio = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        jButton6.setText("jButton1");

        jButton7.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        bottoneBuca4.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca4);
        bottoneBuca4.setBounds(60, 240, 100, 90);

        bottoneBuca1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca1);
        bottoneBuca1.setBounds(60, 60, 100, 90);

        bottoneBuca2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca2);
        bottoneBuca2.setBounds(250, 60, 100, 90);

        bottoneBuca5.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca5);
        bottoneBuca5.setBounds(250, 240, 100, 90);

        bottoneBuca3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca3);
        bottoneBuca3.setBounds(440, 60, 100, 90);

        bottoneBuca6.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.add(bottoneBuca6);
        bottoneBuca6.setBounds(440, 240, 100, 90);

        bottoneGioca.setText("GIOCA");
        bottoneGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneGiocaActionPerformed(evt);
            }
        });
        jPanel1.add(bottoneGioca);
        bottoneGioca.setBounds(560, 130, 100, 40);

        labelPunteggio.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        labelPunteggio.setText("punteggio: 0");
        jPanel1.add(labelPunteggio);
        labelPunteggio.setBounds(560, 170, 140, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneGiocaActionPerformed
       talpa = new Talpa(buche);
       Thread t = new Thread(talpa);
       t.start();
    }//GEN-LAST:event_bottoneGiocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        Interfaccia frame = new Interfaccia();
        frame.setSize(1000,600);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneBuca1;
    private javax.swing.JButton bottoneBuca2;
    private javax.swing.JButton bottoneBuca3;
    private javax.swing.JButton bottoneBuca4;
    private javax.swing.JButton bottoneBuca5;
    private javax.swing.JButton bottoneBuca6;
    private javax.swing.JButton bottoneGioca;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPunteggio;
    // End of variables declaration//GEN-END:variables
}
